






Map<String,String> Subject={
  'APPLIED MATHEMATICS': '001',
'MATRIX COMPUTER METHOD OF STRUCTURAL ANALYSIS': '002',
'STRUCTURAL DYNAMICS': '003',
'THEORY OF ELASTICITY AND PLASTICITY': '004',
'MAINTENANCE AND REHABILITATION OF STRUCTURES': '005',
'CAREER ADVANCEMENT COURSE FOR ENGINEERS - I': '006',
'ADVANCED REINFORCED CONCRETE STRUCTURES': '007',
'ADVANCED STEEL STRUCTURES': '008',
'FINITE ELEMENT METHOD WITH COMPUTER APPLICATION': '009',
'DESIGN OF BRIDGES': '010',
'STABILITY OF STRUCTURES': '011',
'CAREER ADVANCEMENT COURSE FOR ENGINEERS - II': '012',
'DESIGN OF STEEL - CONCRETE COMPOSITE STRUCTURES': '013',
'DISASTER RESISTANT STRUCTURES': '014',
'PRESTRESSED CONCRETE STRUCTURES': '015',
'INDUSTRIAL TRAINING': '016',
'ADVANCED CONCRETE TECHNOLOGY': '017',
'CAREER ADVANCEMENT COURSE FOR ENGINEERS - III': '018',
'PROJECT WORK - PHASE - I': '019',
'PROJECT WORK - PHASE - II': '020',
};

Map<String,String> Code={
  '001': 'APPLIED MATHEMATICS',
  '002': 'MATRIX COMPUTER METHOD OF STRUCTURAL ANALYSIS',
  '003': 'STRUCTURAL DYNAMICS',
  '004': 'THEORY OF ELASTICITY AND PLASTICITY',
  '005': 'MAINTENANCE AND REHABILITATION OF STRUCTURES',
  '006': 'CAREER ADVANCEMENT COURSE FOR ENGINEERS - I',
  '007': 'ADVANCED REINFORCED CONCRETE STRUCTURES',
  '008': 'ADVANCED STEEL STRUCTURES',
  '009': 'FINITE ELEMENT METHOD WITH COMPUTER APPLICATION',
  '010': 'DESIGN OF BRIDGES',
  '011': 'STABILITY OF STRUCTURES',
  '012': 'CAREER ADVANCEMENT COURSE FOR ENGINEERS - II',
  '013': 'DESIGN OF STEEL - CONCRETE COMPOSITE STRUCTURES',
  '014': 'DISASTER RESISTANT STRUCTURES',
  '015': 'PRESTRESSED CONCRETE STRUCTURES',
  '016': 'INDUSTRIAL TRAINING',
  '017': 'ADVANCED CONCRETE TECHNOLOGY',
  '018': 'CAREER ADVANCEMENT COURSE FOR ENGINEERS - III',
  '019': 'PROJECT WORK - PHASE - I',
  '020': 'PROJECT WORK - PHASE - II'
};

String enc_key='AMXYZ';