Map<String,String> BE_Comps={
  'ENGINEERING MATHEMATICS-I':'001',
  'ENGINEERING MATHEMATICS-II TERMWORK':'002',
  'ENGINEERING PHYSICS-II':'003',
  'ENGINEERING PHYSICS-II (TW)':'004',
  'C PROGRAMMING':'005',
  'OOP Language':'006',
  'DSA':'007',
  'ENGINEERING GRAPHICS':'008',
};

Map<String,String> BE_Comps_data={
  '001':'ENGINEERING MATHEMATICS-I',
  '002':'ENGINEERING MATHEMATICS-II TERMWORK',
  '003':'ENGINEERING PHYSICS-II',
  '004':'ENGINEERING PHYSICS-II (TW)',
  '005':'C PROGRAMMING',
  '006':'OOP Language',
  '007':'DSA',
  '008':'ENGINEERING GRAPHICS',
};

String enc_key='AMXYZ';